Fix TypeError when call keystoneclient session.request()
A TypeError raised when run cmd 'heat resource-show':
 TypeError: request() got an unexpected keyword argument
 'follow_redirects'
This problem was introduced by the
change I90bc9d9fcd1058c3eca288f08dd134810f1b0000 to move
SessionClient from HTTPClient to adapter, due there is no
keyword argument 'follow_redirects' in keystoneclient
session.request() method.

Change-Id: I91f13da740bf1e66dffd68cdf666a24d68aa543d
Closes-Bug: #1471650